# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define jobs
jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  sonarqube:
    working_directory: ~/build
    docker:
      - image: sonarsource/sonar-scanner-cli
        # Use CircleCI's resource classes for scaling resources.
        # See https://circleci.com/docs/2.0/configuration-reference/#resource_class
        resource_class: small
    steps:
      - checkout  # Ensure the source code is available in the workspace.
      - run: find .  # Example command to confirm the source files.
      - run:
          name: SonarQube Analysis
          command: |
            SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
            echo "Sonar branch value is: $SONAR_BRANCH"
            echo "Sonar org value is: $SONAR_ORG"
            sonar-scanner \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.organization="$SONAR_ORG" \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.exclusions="**/android/**,**/ios/**" \
              -Dsonar.login="$SONAR_TOKEN" \
              -Dsonar.branch.name="$SONAR_BRANCH" \
              -Dsonar.sources="."
          
# Workflows orchestrating the jobs
workflows:
  version: 2
  build-and-analyze:
    jobs:
      - say-hello
      - sonarqube:
          requires:
            - say-hello
